/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface GameOfLife {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLGameOfLifeElement extends Components.GameOfLife, HTMLStencilElement {
    }
    var HTMLGameOfLifeElement: {
        prototype: HTMLGameOfLifeElement;
        new (): HTMLGameOfLifeElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "game-of-life": HTMLGameOfLifeElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface GameOfLife {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "game-of-life": GameOfLife;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "game-of-life": LocalJSX.GameOfLife & JSXBase.HTMLAttributes<HTMLGameOfLifeElement>;
        }
    }
}
